#
# Copyright (c) 2019-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Build

on:
  schedule:
    - cron: '00 21 * * *'

  pull_request:
    branches:
      - '*'

concurrency:
  group: main-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  Linux_RelWithDebInfo:
    uses: ./.github/workflows/linux.yml
    with:
      platform: ubuntu-22.04
      build_type: RelWithDebInfo
      osquery_toolchain_version: 1.1.0

  Linux_Debug:
    uses: ./.github/workflows/linux.yml
    with:
      platform: ubuntu-22.04
      build_type: Debug
      osquery_toolchain_version: 1.1.0

